<?php
/**
 * Left-hand "Shop Filters" sidebar on the shop and product category pages,
 * built on Kadence's existing sidebar/layout system (register a sidebar,
 * then force Kadence to show it as a left sidebar on shop pages) rather
 * than hand-rolling a new column layout.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'widgets_init', 'hugginbutt_register_shop_sidebar' );

function hugginbutt_register_shop_sidebar() {
	register_sidebar(
		array(
			'name'          => __( 'Shop Filters', 'hugginbutt-child' ),
			'id'            => 'hb-shop-filters',
			'description'   => __( 'Widgets shown in the left-hand filter panel on the shop and product category pages.', 'hugginbutt-child' ),
			'before_widget' => '<div class="hb-shop-filter-widget widget %2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h3 class="hb-shop-filter-widget__title widget-title">',
			'after_title'   => '</h3>',
		)
	);
}

add_filter( 'kadence_post_layout', 'hugginbutt_force_shop_sidebar' );

function hugginbutt_force_shop_sidebar( $layout ) {
	if (
		class_exists( 'WooCommerce' ) &&
		( is_shop() || is_product_category() || is_product_tag() ) &&
		is_active_sidebar( 'hb-shop-filters' )
	) {
		$layout['sidebar']    = 'enable';
		$layout['side']       = 'left';
		$layout['sidebar_id'] = 'hb-shop-filters';
	}

	return $layout;
}

/**
 * Keeps category filtering on the single Shop page instead of navigating to
 * separate category archive pages: rewrites product_cat term links (as
 * generated by the Categories widget/block, whichever is in use) into
 * ?product_cat=slug links on the Shop URL, carrying over any other active
 * filters (price, attributes) already in the query string. Clicking the
 * already-active category toggles the filter back off.
 */
add_filter( 'term_link', 'hugginbutt_shop_category_filter_link', 10, 3 );

function hugginbutt_shop_category_filter_link( $url, $term, $taxonomy ) {
	if ( 'product_cat' !== $taxonomy || ! function_exists( 'is_shop' ) || ! is_shop() || is_search() ) {
		return $url;
	}

	$shop_url     = wc_get_page_permalink( 'shop' );
	$current_slug = isset( $_GET['product_cat'] ) ? sanitize_title( wp_unslash( $_GET['product_cat'] ) ) : '';

	$args = hugginbutt_shop_filter_query_args();

	if ( $term->slug === $current_slug ) {
		unset( $args['product_cat'] );
	} else {
		$args['product_cat'] = $term->slug;
	}

	return $args ? add_query_arg( $args, $shop_url ) : $shop_url;
}

/**
 * Adds an "All" link at the top of the Categories widget list, so shoppers
 * can clear the category filter without a dedicated reset control. WP core's
 * wp_list_categories() points show_option_all at get_post_type_archive_link()
 * for non-post taxonomies, which for product_cat resolves to the Shop page
 * itself - already exactly the "clear filter" URL we want, no rewriting
 * needed.
 */
add_filter( 'woocommerce_product_categories_widget_args', 'hugginbutt_shop_categories_widget_all_option' );

function hugginbutt_shop_categories_widget_all_option( $args ) {
	if ( function_exists( 'is_shop' ) && is_shop() && ! is_search() ) {
		$args['show_option_all'] = __( 'All', 'hugginbutt-child' );
	}

	return $args;
}

/**
 * Whitelisted subset of the current request's query string that should be
 * preserved when rewriting filter links (product_cat, price, attributes) —
 * deliberately not the whole of $_GET, so unrelated params can't leak into
 * generated links.
 */
function hugginbutt_shop_filter_query_args() {
	$args = array();

	foreach ( array( 'product_cat', 'min_price', 'max_price', 'orderby', 'rating_filter' ) as $key ) {
		if ( isset( $_GET[ $key ] ) && '' !== $_GET[ $key ] ) {
			$args[ $key ] = sanitize_text_field( wp_unslash( $_GET[ $key ] ) );
		}
	}

	foreach ( $_GET as $key => $value ) {
		if ( 0 === strpos( $key, 'filter_' ) || 0 === strpos( $key, 'query_type_' ) ) {
			$args[ $key ] = sanitize_text_field( wp_unslash( $value ) );
		}
	}

	return $args;
}

/**
 * Applies the ?product_cat=slug query param as a tax_query on the Shop
 * page's main product query, so the filtered products render in place
 * instead of requiring a visit to the category archive.
 */
add_action( 'pre_get_posts', 'hugginbutt_filter_shop_by_category' );

function hugginbutt_filter_shop_by_category( $query ) {
	if ( is_admin() || ! $query->is_main_query() || ! function_exists( 'is_shop' ) || ! is_shop() || is_search() ) {
		return;
	}

	if ( empty( $_GET['product_cat'] ) ) {
		return;
	}

	$slug = sanitize_title( wp_unslash( $_GET['product_cat'] ) );
	$term = get_term_by( 'slug', $slug, 'product_cat' );

	if ( ! $term || is_wp_error( $term ) ) {
		return;
	}

	$tax_query   = (array) $query->get( 'tax_query' );
	$tax_query[] = array(
		'taxonomy' => 'product_cat',
		'field'    => 'slug',
		'terms'    => $slug,
	);

	$query->set( 'tax_query', $tax_query );
}
